/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'RTOS_RT-Thread' 
 * Target:  'APM32F072' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "apm32f0xx.h"



#endif /* RTE_COMPONENTS_H */
